blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('<slug:slug>', views.RecipeDetail.as_view(), name='recipe_detail'),
    path(
        'favourited/<slug:slug>',
        views.RecipeFavourite.as_view(),
        name='recipe_favourited'
    ),
    path(
        'comment_confirm_delete/<int:pk>',
        views.DeleteComment.as_view(),
        name='comment_confirm_delete'
    ),
    path(
        'comment_update_form/<int:pk>',
        views.EditComment.as_view(),
        name='comment_update_form'
    ),
    path(
        'create_recipe_form/',
        views.CreateRecipe.as_view(),
        name='create_recipe_form'
    ),
    path('favourites/', views.FavouritesList.as_view(), name='favourites'),
    path('my_recipes/', views.MyRecipesList.as_view(), name='my_recipes'),
]

everybodys_recipes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django_summernote.fields import SummernoteTextField

STATUS = ((0, 'Draft'), (1, 'Published'))


class Recipe(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipe_post'
    )
    date_created = models.DateTimeField(auto_now_add=True)
    recipe_photo = CloudinaryField('image', default='placeholder')
    description = SummernoteTextField()
    ingredients = SummernoteTextField()
    instructions = SummernoteTextField()
    favourited = models.ManyToManyField(
        User, related_name='favourited_recipes', blank=True
    )
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title

    def favourited_count(self):
        return self.favourited.count()


class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='comments'
    )
    name = models.CharField(max_length=80)
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    edited = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from crispy_forms.helper import FormHelper
from .models import Comment, Recipe
from django import forms
from django.forms import inlineformset_factory


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body': ""}
        label_suffix = ''


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = (
            'title',
            'recipe_photo',
            'description',
            'ingredients',
            'instructions',
        )

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.text import slugify
from .models import Recipe, Comment
from .forms import (CommentForm, RecipeForm)


class RecipeList(generic.ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-date_created')
    template_name = 'index.html'
    paginate_by = 9


class FavouritesList(generic.ListView):
    model = Recipe
    template_name = 'favourites.html'
    paginate_by = 9

    def get_queryset(self):
        return Recipe.objects.filter(
            status=1,
            favourited=self.request.user.id
            ).order_by('-date_created')


class MyRecipesList(generic.ListView):
    model = Recipe
    template_name = 'my_recipes.html'
    paginate_by = 9

    def get_queryset(self):
        return Recipe.objects.filter(
            status=1,
            author=self.request.user.id
            ).order_by('-date_created')


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.order_by('date_created')
        favourited = False
        if recipe.favourited.filter(id=self.request.user.id).exists():
            favourited = True

        return render(
            request,
            'recipe_detail.html',
            {
                'recipe': recipe,
                'comments': comments,
                'commented': False,
                'favourited': favourited,
                'comment_form': CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(
            approved=True).order_by('date_created')
        favourited = False
        if recipe.favourited.filter(id=self.request.user.id).exists():
            favourited = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.save()
            messages.success(request, 'Your comment is awaiting approval')
            return HttpResponseRedirect(request.path_info)
        else:
            comment_form = CommentForm()

        return render(
            request,
            'recipe_detail.html',
            {
                'recipe': recipe,
                'comments': comments,
                'commented': True,
                'favourited': favourited,
                'comment_form': CommentForm()
            },
        )


class RecipeFavourite(View):

    def post(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)

        if recipe.favourited.filter(id=request.user.id).exists():
            recipe.favourited.remove(request.user)
        else:
            recipe.favourited.add(request.user)

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


class DeleteComment(LoginRequiredMixin,
                    UserPassesTestMixin,
                    generic.DeleteView):
    model = Comment
    template_name = 'comment_confirm_delete.html'

    def test_func(self):
        comment = self.get_object()
        return self.request.user.username == comment.name

    def get_success_url(self):
        recipe = self.object.recipe
        messages.success(self.request, 'Your comment has been deleted')
        return reverse_lazy('recipe_detail', args=[recipe.slug])


class EditComment(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Comment
    fields = ['body']
    template_name = 'comment_update_form.html'

    def test_func(self):
        comment = self.get_object()
        return self.request.user.username == comment.name

    def get_success_url(self):
        recipe = self.object.recipe
        messages.success(
            self.request,
            'Your comment has been edited and is awaiting approval'
        )
        return reverse_lazy('recipe_detail', args=[recipe.slug])

    def form_valid(self, form):
        form.instance.approved = False
        form.instance.edited = True
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class CreateRecipe(LoginRequiredMixin, generic.CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'create_recipe_form.html'
    success_url = '/my_recipes/'

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if (form.is_valid()):
            form.instance.author_id = request.user.id
            form.instance.slug = slugify(form.instance.title)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        messages.success(
            self.request,
            'Your recipe has been uploaded and will\
             be published by the administrator'
        )
        return HttpResponseRedirect(self.get_success_url())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">
    </script>
    <title>Everybody's Recipes</title>
</head>
<body>

    <!-- Navigation based on bootstrap navbar
    https://getbootstrap.com/docs/5.3/components/navbar -->
    
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand mb-0 h1" href="{% url 'home' %}">Everybody's Recipes</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse fw-medium" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'my_recipes' %}">My Recipes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'favourites' %}">My Favourites</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Signed in as: {{ user.username }}
                </a>
                <ul class="dropdown-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_recipe_form' %}">Create a Recipe</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
                  </li>
                </ul>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
    </nav>

    <!-- Message alert -->
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissable fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        </div>
      </div>
    </div>
    

    <main>
        <h1 class="text-center">{% block heading %}{% endblock %}</h1>

        {% block content %}

        {% endblock content %}
    </main>

<script>
      setTimeout(function() {
        let messages = document.getElementById("msg");
        let alert = new bootstrap.Alert(messages);
        alert.close();
      }, 3000);
    </script>
</body>
</html>

templates/comment_confirm_delete.html
{% extends 'base.html' %}

{% block heading %}
Delete Comment
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center align-items-center">
        <div class="col-xs-12 col-sm-8 col-md-4 mt-3">
            <form method="post">
                {% csrf_token %}
                <h5>Are you sure you want to delete this comment?</h5>
                <p>{{ comment.body }}</p>
                <button class="btn btn-light mt-3" type="submit" value="Confirm">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/comment_update_form.html
{% extends 'base.html' %}

{% block heading %}
Edit Comment
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center align-items-center">
        <div class="col-xs-12 col-sm-8 col-md-4 mt-3">
            <form method="post">{% csrf_token %}
                {{ form.body }}
                <br>
                <button class="btn btn-light mt-3" type="submit" value="Update">Update</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/create_recipe_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block heading %}
Create Recipe
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-sm-center">
        <div class="col-sm-8 col-md-6 mt-3">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-light mt-3" type="submit" value="Save">Create Recipe</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/favourites.html
{% extends 'index.html' %}
{% block heading %}
My Favourites
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block heading %}
All Recipes
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row mt-4">
        {% for recipe in recipe_list %}
        <div class="col-md-4">
            <div class="card mb-4">
                <a href="{% url 'recipe_detail' recipe.slug %}" class="btn" style="background-color: white;">
                    {% if 'placeholder' in recipe.recipe_photo.url %}
                    <img src="https://res.cloudinary.com/dbnrqjev4/image/upload/v1690840285/pexels-fauxels-3184183_vgtkgv.jpg" class="card-img-top" alt="...">
                    {% else %}
                    <img src="{{ recipe.recipe_photo.url }}" class="card-img-top recipe-img-home" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <h3 class="card-title">{{ recipe.title }}</h3>
                        <h4 class="card-subtitle">By: {{ recipe.author }}</h4>
                    </div>
                </a>
                <div class="card-footer">
                    <p class="card-text text-muted h6">
                        {{ recipe.date_created | date:'M d, Y' }}
                        <span class="float-end">
                            {% with recipe.comments.count as total_comments %}
                            <i class="fa-regular fa-comment"></i>
                            {{ total_comments }}&nbsp;&nbsp;
                            {% endwith %}
                            <i class="fa-sharp fa-regular fa-heart"></i>
                            &nbsp;{{ recipe.favourited_count }}
                        </span>
                    </p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
    </div>
    <div class="row mt-4">
        {% endif %}
        {% endfor %}
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-light">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-light"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

templates/my_recipes.html
{% extends 'index.html' %}
{% block heading %}
My Recipes
{% endblock %}

templates/recipe_detail.html
{% extends 'base.html' %}

{% block heading %}
{{ recipe.title }}
{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row text-center">
        <h5>By: {{ recipe.author }}</h5>
    </div>

    <div class="row justify-content-center">
        <div class="col align-self-center text-center">
            <div class="row mb-2">
            {% with comments.count as total_comments %}
                <span>
                    <i class="fa-regular fa-comment"></i>
                    {{ total_comments }}&nbsp;
            {% endwith %}
                    &nbsp;<i class="fa-sharp fa-regular fa-heart"></i>
                    {{ recipe.favourited_count }}
                </span>
            </div>
        {% if user.is_authenticated %}
        <form action="{% url 'recipe_favourited' recipe.slug %}" method="POST" class="d-inline">
            {% csrf_token %}
            {% if favourited %}            
            <button class="btn btn-light mb-2" type="submit" name="favourited_id" value="{{ recipe.slug }}">
                <span>Favourited</span>
                <i class="fa-sharp fa-solid fa-heart"></i>
            </button>
            {% else %}            
            <button class="btn btn-light mb-2" type="submit" name="favourited_id" value="{{ recipe.slug }}">
                <span>Add to Favourites</span>
                <i class="fa-sharp fa-regular fa-heart"></i>
            </button>
            {% endif %}
        </form>
        {% endif %}
        </div>
    </div>

    <div class="row justify-content-sm-center text-center">
        <div class="col-xl-6 col-lg-8 col-md-10 mb-5">
            {% if 'placeholder' in recipe.recipe_photo.url %}
            <img src="https://res.cloudinary.com/dbnrqjev4/image/upload/v1690840285/pexels-fauxels-3184183_vgtkgv.jpg" class="card-img-top" alt="...">
            {% else %}
            <img src="{{ recipe.recipe_photo.url }}" class="card-img-top" alt="...">
            {% endif %}
            <h3>Description</h3>
            {{ recipe.description | safe }}
            <div class="row recipe-method p-0">
                <div class="col-sm-5 mb-3">
                    <div class="card">
                        <h3>Ingredients</h3>
                        <div class="text-start m-2">
                            {{ recipe.ingredients | safe }}
                        </div>
                    </div>
                </div>
                <div class="col-sm-7 mb-3">
                    <div class="card">
                        <h3>Instructions</h3>
                        <div class="text-start mt-2 me-3">
                            {{ recipe.instructions | safe }}
                        </div>                        
                    </div>
                </div>
            </div>
            
            <div class="row mt-3 mx-0">
                <div class="card p-0">
                    <h3>Comments</h3>
                    <hr>
                    <div class="card-body text-start">
                        {% for comment in comments %}
                        <p class="fw-bold">
                            {{ comment.name }}
                            <span class="fs-6 fw-light">commented on {{ comment.date_created }}</span>
                        </p>
                        {% if comment.approved %}
                        <p>
                            {{ comment.body }}
                        </p>
                        {% elif comment.edited and comment.approved %}
                        <p class="fs-6 fw-light fst-italic">
                            Edited on {{ comment.date_edited }}
                        </p>
                        {% elif comment.edited and not comment.approved %}
                        <p class="fs-6 fst-italic">
                            This comment has been edited and is awaiting approval
                        </p>
                        {% else %}
                        <p class="fs-6 fst-italic">
                            This comment is awaiting approval
                        </p>
                        {% endif %}

                        {% if user.is_authenticated %}
                            {% if comment.name == user.username %}
                            <a class="btn btn-light" href="{% url 'comment_update_form' comment.id %}">Edit Comment</a>
                            <a class="btn btn-light" href="{% url 'comment_confirm_delete' comment.id %}">Delete Comment</a>
                            {% endif %}
                        {% endif %}
                        
                        <hr>
                        {% endfor %}

                        {% if user.is_authenticated %}
                        <h5 class="text-center">Leave a comment</h5>
                            <p>Commenting as: <span class="fw-bold">{{ user.username }}</span></p>
                            <form method="POST">
                                {{ comment_form | crispy }}
                                {% csrf_token %}
                                <button class="btn btn-light mt-3" type="submit">Submit</button>
                            </form>
                        {% else %}
                        <h5><a class="btn btn-light" href="{% url 'account_login' %}">Sign in</a> to comment</h5>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}